"""Project-vocabulary layer: per-file LLM summaries embedded in their own Qdrant
collection to fix the concept→symbol "anchor" problem.

A vague natural-language question ("where are push notifications handled?") embeds
near the *summary* of the right file ("...FcmReceiveService handles FCM push
notifications...") even when it embeds far from the raw code. Searching this
collection surfaces the canonical file/symbol that semantic code search buries,
giving /smart-search extra grounding anchors to resolve exactly.

Summaries are plain TEXT (generated by agy/Gemini on the Mac + gemma4 on the GPU,
keyed by repo-relative path) — regenerable anytime, generator-agnostic.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import structlog

from rag.core.vectorstore import ChunkDocument, QdrantVectorStore

logger = structlog.get_logger()

VOCAB_SUFFIX = "_vocab"


def vocab_collection_for(code_collection: str) -> str:
    """Vocab collection name derived from a repo's code collection."""
    return f"{code_collection}{VOCAB_SUFFIX}"


def load_summaries(jsonl_path: str | Path) -> list[dict[str, Any]]:
    """Load {file, summary} records, dropping ERROR/empty summaries.

    Records are keyed by repo-relative path so Mac (agy) and remote (gemma4)
    outputs merge cleanly; later records win on duplicate paths.
    """
    merged: dict[str, str] = {}
    skipped = 0
    with open(jsonl_path, errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except Exception:
                skipped += 1
                continue
            f = rec.get("file")
            s = (rec.get("summary") or "").strip()
            if not f or not s or s.startswith("ERROR"):
                skipped += 1
                continue
            merged[f] = s
    logger.info("vocab_summaries_loaded", path=str(jsonl_path), kept=len(merged), skipped=skipped)
    return [{"file": f, "summary": s} for f, s in merged.items()]


def build_vocab_docs(records: list[dict[str, Any]], repo: str) -> list[ChunkDocument]:
    """Turn {file, summary} records into ChunkDocuments for upsert.

    content = the summary text (this is what gets embedded — the concept→symbol
    bridge). The file stem is stored as ``name`` so /smart-search can feed it
    into exact resolve as a grounding anchor.
    """
    docs: list[ChunkDocument] = []
    for rec in records:
        rel = rec["file"]
        summary = rec["summary"]
        stem = Path(rel).stem
        ext = Path(rel).suffix.lstrip(".")
        content_hash = hashlib.sha256(f"{rel}:{summary}".encode()).hexdigest()
        docs.append(
            ChunkDocument(
                content=summary,
                chunk_id=f"{repo}:vocab:{rel}",
                metadata={
                    "file_path": rel,
                    "name": stem,
                    "summary": summary,
                    "repo": repo,
                    "language": ext,
                    "chunk_type": "vocab_summary",
                    "content_hash": content_hash,
                },
            )
        )
    return docs


async def collection_exists(vectorstore: QdrantVectorStore, collection: str) -> bool:
    try:
        client = await vectorstore._get_client()
        cols = await client.get_collections()
        return collection in {c.name for c in cols.collections}
    except Exception:
        return False


async def search_vocab(
    vectorstore: QdrantVectorStore,
    collection: str,
    query: str,
    top_k: int = 5,
) -> list[dict[str, Any]]:
    """Semantic search over the vocab collection.

    Returns [{file_path, name, summary, score}] for the closest file summaries,
    or [] if the collection doesn't exist yet (vocab layer not built).
    """
    if not await collection_exists(vectorstore, collection):
        return []
    results = await vectorstore.search(collection=collection, query=query, top_k=top_k)
    out: list[dict[str, Any]] = []
    for r in results:
        p = r.payload or {}
        out.append(
            {
                "file_path": p.get("file_path", ""),
                "name": p.get("name", ""),
                "summary": p.get("summary", p.get("content", "")),
                "score": r.score,
            }
        )
    return out
